### ISSUE TITLE
MyHome - Home Automation IOS app crashes

### ISSUE THREAD

**Issue by Doughboy68** [rodtoll/homebridge-isy-js#17]
I can cause the home bridge server to crash every time by pressing "Tap to identify" within a device. 

Not sure if this is bug with MyHome app or homebridge-isy-js but based on the output it may since the error happens in the homebridge-isy-js/... here is the text of app crashing on my Raspberry Pi:

Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-isy-js/index.js:482
        this.device.sendLightCommand(false, function(result) {
                   ^

TypeError: Cannot read property 'sendLightCommand' of undefined
    at /usr/local/lib/node_modules/homebridge-isy-js/index.js:482:14
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:673:13)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:229:10)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:161:20
    at IncomingMessage.parsers.auto (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:402:7)
    at Request.mixin._encode (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:198:29)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:157:16
    at Request.mixin._decode (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:173:7)
pi@raspberrypi:~ $

**Comment by rodtoll** [comment]
@Doughboy68 - Thanks for the bug report. Not sure yet how I'll address this -- I never did get around to writing an implementation for identify. I'll add to my worklist making this not crash though. I'll see if I can use the Insteon beep function so that identify does something useful.

**Comment by rodtoll** [comment]
Resolved in plugin v0.1.6.
