### ISSUE TITLE
crash data

### ISSUE THREAD

**Issue by psmith3** [rodtoll/homebridge-isy-js#25]
Hi, any idea what this crash data could be from? I have the docker container set to --restart=always, but it did not..

```
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
stderr
19:04:49
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
stderr
19:04:49
         ^
stderr
19:04:49
stderr
19:04:49
Error: dns service error: unknown
stderr
19:04:49
    at Error (native)
stderr
19:04:49
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
stderr
19:04:49
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
stderr
19:04:49
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
stderr
19:04:49
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:498:20)
stderr
19:04:49
    at emitNone (events.js:80:13)
stderr
19:04:49
    at HAPServer.emit (events.js:179:7)
stderr
19:04:49
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:169:8)
stderr
19:04:49
    at emitNone (events.js:80:13)
stderr
19:04:49
    at EventedHTTPServer.emit (events.js:179:7)
```

**Comment by rodtoll** [comment]
@TheHavocHero 

This is outside of the plugin, inside the HomeBridge core library. I would see if they can help. You can find the root project here: https://github.com/nfarina/homebridge

Looking at the stack it looks like it is a failure in the mdns node.js library. And the library looks like it is failing in startup so perhaps that's why docker isn't restarting? I don't have a lot of experience with docker so I'm not sure. 

Another option would be to ask about docker compatibility at the mdns project page here: https://github.com/agnat/node_mdns

**Comment by psmith3** [comment]
Thanks. Should have posted to the root project. Thanks for the direction.
