### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of null

### ISSUE THREAD

**Issue by mmancini403** [rodtoll/homebridge-isy-js#30]
HI.  I am trying to get this to run but have not had any success.  Here's the error code I am receiving:

[9/5/2016, 11:51:17 AM] [isy-js] Initializing isy-js platform...
/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:404
        if (response instanceof Error || response.statusCode != 200) {
                                                 ^

TypeError: Cannot read property 'statusCode' of null
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:404:50)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireError (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:207:10)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:246:14)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnData (_http_client.js:327:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

If anyone can point me in the right direction, I'd be very appreciative!

**Comment by mmancini403** [comment]
Ok.  Got it fixed by following instructions here from user DavidG:

http://forum.universal-devices.com/topic/16329-homekit-support-via-homebridge-siri-voice-control/page-3#entry172273

"""Go into the ISY and create a variable under the integer tab.  The homebridge code isn't smart enough to continue if you have no integer variables setup.  I just clicked new, then save, back to homebridge and it works."""
