### ISSUE TITLE
Error: dns service error: name conflict

### ISSUE THREAD

**Issue by RGKS** [rodtoll/homebridge-isy-js#34]
I'm getting the following error when running Homebridge. Any Ideas?

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement](/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:524:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:183:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)

**Comment by RGKS** [comment]
restarted Raspberry Pi and fixed issue.
