### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by mpr131** [rodtoll/homebridge-isy-js#48]
Hi all...I keep getting this error when trying to start:

[2/19/2017, 4:25:52 PM] Homebridge is running on port 51826.
2017-1-0#16:25:52- ISY-JS: Error loading variables from isy. Device likely doesn't have any variables defined. Safe to ignore.
[2/19/2017, 4:25:52 PM] [isy-mpr1310] 117-1-0#16:25:52- ISYPLATFORM: Filtered device has: 13 devices
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at /usr/local/lib/node_modules/homebridge-isy-js/index.js:207:3
    at ISY.finishInitialize (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:368:5)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:539:30
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:410:13)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:229:10)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:161:20
    at IncomingMessage.auto (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:402:7)
    at Request._encode (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:198:29)
    at /usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:157:16
    at Request._decode (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:173:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:150:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

Here is a copy of my json file:

{
   "bridge":{
      "name":"TaylorSt",
      "username":"AC:12:3D:E3:CE:23",
      "port":51826,
      "pin":"134-22-223"
   },
   "platforms":[
      {
         "platform":"isy-js",
         "name":"isy-mpr1310",
         "host":"192.168.1.206",
         "username":"admin",
         "password":"admin",
         "elkEnabled":false,
         "useHttps":false,
         "debugLoggingEnabled":true,
         "includeAllScenes":false,
         "ignoreDevices":[

         ]
      }
   ]
}

I've tried uninstalling and reinstalling and tried resetting the ISY and PLM to default, but still am having no luck.

Any help on this is appreciated.

**Comment by rodtoll** [comment]
This happens when the ISY you are connecting to does not have any variables
defined. Make sure you have a minimum of one of each type of variable and
this error should go away.

**Comment by mpr131** [comment]
many thanks!  this fixed it.
