### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by CVHvisuals** [rodtoll/homebridge-isy-js#60]
I am unable to install the latest version of homebridge-isy-js. Is it possible to install another version?

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'github:pradeepmouli/homebridge-isy-js'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.6.0
4 verbose npm-session ed85201011a99497
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 verbose prepareGitDep undefined: installing devDeps and running prepare script.
8 error prepareGitDep 1>
8 error prepareGitDep > curve25519-n@1.4.0 install /Users/cvanhoose/.npm/_cacache/tmp/git-clone-ff35735e/node_modules/curve25519-n
8 error prepareGitDep > node-gyp rebuild
9 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep gyp ERR! configure error
9 error prepareGitDep gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/cvanhoose/.npm/_cacache/tmp/git-clone-ff35735e/node_modules/curve25519-n/build'
9 error prepareGitDep gyp ERR! System Darwin 18.7.0
9 error prepareGitDep gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
9 error prepareGitDep gyp ERR! cwd /Users/cvanhoose/.npm/_cacache/tmp/git-clone-ff35735e/node_modules/curve25519-n
9 error prepareGitDep gyp ERR! node -v v12.6.0
9 error prepareGitDep gyp ERR! node-gyp -v v5.0.3
9 error prepareGitDep gyp ERR! not ok
9 error prepareGitDep npm ERR! code ELIFECYCLE
9 error prepareGitDep npm ERR! errno 1
9 error prepareGitDep npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
9 error prepareGitDep npm ERR! Exit status 1
9 error prepareGitDep npm ERR!
9 error prepareGitDep npm ERR! Failed at the curve25519-n@1.4.0 install script.
9 error prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9 error prepareGitDep
9 error prepareGitDep npm ERR! A complete log of this run can be found in:
9 error prepareGitDep npm ERR!     /Users/cvanhoose/.npm/_logs/2019-07-26T01_06_24_672Z-debug.log
10 silly fetchPackageMetaData error for github:pradeepmouli/homebridge-isy-js premature close
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 31233ms
13 verbose stack Error: premature close
13 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
13 verbose stack     at PassThrough.emit (events.js:208:15)
13 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
13 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
14 verbose cwd /Users/cvanhoose
15 verbose Darwin 18.7.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "github:pradeepmouli/homebridge-isy-js"
17 verbose node v12.6.0
18 verbose npm  v6.10.2
19 error premature close
20 verbose exit [ 1, true ]

**Comment by PaulWieland** [comment]
Did you try the forked version?

**Comment by CVHvisuals** [comment]
github:pradeepmouli/homebridge-isy-js
is what I am trying to install and receiving the error above. 
The latest version from that fork is 0.2.5
I am able to install 0.1.9 with no issues. 
Is it possible to install another version of 0.2.x?

**Comment by PaulWieland** [comment]
Hopefully @pradeepmouli will see this. Forked branches don't have their own issue's tab apparently, but rodtoll isn't maintaining the codebase anymore.

**Comment by pradeepmouli** [comment]
Saw it! Will try to get to this ASAP. Haven’t had a chance to look into this for a while. I think the issue is that I had merged “v5” of Isy-js into the master code base. Repointing the isy-is dependency in homebridge-Isy-is May work.

**Comment by CVHvisuals** [comment]
that would be great. Thank you for your help.

**Comment by TechRemarker** [comment]
Was this resolved? Or is the fork install not working for new installs? Was planning on setting up tonight on Synlogy docker container that already has Homebridge setup.

**Comment by TechRemarker** [comment]
@pradeepmouli Tried installing but oddly this fork is not available in npm so its not listed as an option to install in docker so ran "npm install github:pradeepmouli/homebridge-isy-js" to manually install but shows all of these errors:

/homebridge # npm install github:pradeepmouli/homebridge-isy-js
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated homebridge-lib@1.0.11: Latest version: 3.0.1
npm ERR! prepareGitDep npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep npm ERR! prepareGitDep > core-js@2.6.9 postinstall /root/.npm/_cacache/tmp/git-clone-67ef8540/node_modules/babel-preset-env/node_modules/core-js
npm ERR! prepareGitDep npm ERR! prepareGitDep > node scripts/postinstall || echo "ignore"
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
npm ERR! prepareGitDep npm ERR! prepareGitDep > https://opencollective.com/core-js 
npm ERR! prepareGitDep npm ERR! prepareGitDep > https://www.patreon.com/zloirock 
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep > isy-js@0.5.0 prepare /root/.npm/_cacache/tmp/git-clone-67ef8540
npm ERR! prepareGitDep npm ERR! prepareGitDep > tsc
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! prepareGitDep sh: tsc: not found
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! isy-js@0.5.0 prepare: `tsc`
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! Failed at the isy-js@0.5.0 prepare script.
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR! prepareGitDep npm ERR!     /root/.npm/_logs/2019-08-24T23_13_56_329Z-debug.log
npm ERR! prepareGitDep npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! premature close
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /root/.npm/_logs/2019-08-24T23_13_56_494Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-24T23_13_58_113Z-debug.log

**Comment by pradeepmouli** [comment]
Try installing without the dev option

**Comment by TechRemarker** [comment]
@pradeepmouli Thanks, so instead of "npm install github:pradeepmouli/homebridge-isy-js" what specific command should one use when doing a fresh install to avoid any errors as imagine you may want that on your readme since it would be required for new installations?

**Comment by pradeepmouli** [comment]
Oh. So the dev flag wasn’t being used. The issue may be the version of node.... I didn’t run it on a recent version.... try v10 or lower.

**Comment by TechRemarker** [comment]
@pradeepmouli Only, "npm install github:pradeepmouli/homebridge-isy-js" was used (since it's not available in NPM for some reason).

It's a fresh install all using the latest versions available. Ironically, I tried installing the rod's discontinued homebridge-isy-js that hasn't been updated in years, but that installed perfectly from NPM with no issues. So going to stick with that one for now, but once this version is working from NPM using all the standard latest libraries without errors, do let us know so people can try it out again as I imagine eventually rod's version will break some day. Thank you!

**Comment by CVHvisuals** [comment]
Same issue. Tried with versions from node 7 and up with the same result. Unable to install with the same error log.

**Comment by CVHvisuals** [comment]
Has anyone found a workaround to install?

**Comment by PaulWieland** [comment]
I’m rebuilding my home automation server on a raspi, and my new insteon to HomeKit link is going to be done with node red instead of home bridge. 

There is a node red node based on the HAP JS library. My plan is to write a new node on top of the existing Insteon plm library which provides an interface directly from the Insteon PLM to node red. 

I will post an update here when I have an example to show, but I would strongly encourage anyone interested in home automation to check out node red.
